/**
 * SEARCH.java
 *
 *  This file is automatically generated by PML API 
 *	generated on  Wed Oct 24 15:11:30 EDT 2007
 *  
 *  @author: Li Ding (http://www.cs.rpi.edu/~dingl )
 *
 */
package  org.inference_web.iwapp.iwsearch;

import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.ResourceFactory;


/**
 *
 *  
 *  Ontology information 
 *   	label:  Search Service Ontology@en-US
 *   	comment:   This ontology defines some common terms for representing information tranferred between a client and a search engine. This ontology is create by Li Ding (http://www.cs.rpi.edu/~dingl/).
  @en-US
 */
public class SEARCH{

    protected static final String NS = "http://inference-web.org/2007/10/service/search.owl#";

    public static final String getURI(){ return NS; }

	// Class (3)
	 public final static String SearchResponse_lname = "SearchResponse";
	 public final static String SearchResponse_uri = "http://inference-web.org/2007/10/service/search.owl#SearchResponse";
	 public final static Resource  SearchResponse = ResourceFactory.createResource(SearchResponse_uri);

	 public final static String SearchRequest_lname = "SearchRequest";
	 public final static String SearchRequest_uri = "http://inference-web.org/2007/10/service/search.owl#SearchRequest";
	 public final static Resource  SearchRequest = ResourceFactory.createResource(SearchRequest_uri);

	 public final static String SearchService_lname = "SearchService";
	 public final static String SearchService_uri = "http://inference-web.org/2007/10/service/search.owl#SearchService";
	 public final static Resource  SearchService = ResourceFactory.createResource(SearchService_uri);

	// Property (14)
	 public final static String hasSearchResults_lname = "hasSearchResults";
	 public final static String hasSearchResults_uri = "http://inference-web.org/2007/10/service/search.owl#hasSearchResults";
	 public final static Property  hasSearchResults = ResourceFactory.createProperty(hasSearchResults_uri);

	 public final static String hasSearchErrorMessage_lname = "hasSearchErrorMessage";
	 public final static String hasSearchErrorMessage_uri = "http://inference-web.org/2007/10/service/search.owl#hasSearchErrorMessage";
	 public final static Property  hasSearchErrorMessage = ResourceFactory.createProperty(hasSearchErrorMessage_uri);

	 public final static String hasSearchString_lname = "hasSearchString";
	 public final static String hasSearchString_uri = "http://inference-web.org/2007/10/service/search.owl#hasSearchString";
	 public final static Property  hasSearchString = ResourceFactory.createProperty(hasSearchString_uri);

	 public final static String hasSearchStart_lname = "hasSearchStart";
	 public final static String hasSearchStart_uri = "http://inference-web.org/2007/10/service/search.owl#hasSearchStart";
	 public final static Property  hasSearchStart = ResourceFactory.createProperty(hasSearchStart_uri);

	 public final static String hasSearchReturnedResults_lname = "hasSearchReturnedResults";
	 public final static String hasSearchReturnedResults_uri = "http://inference-web.org/2007/10/service/search.owl#hasSearchReturnedResults";
	 public final static Property  hasSearchReturnedResults = ResourceFactory.createProperty(hasSearchReturnedResults_uri);

	 public final static String hasSearchLimit_lname = "hasSearchLimit";
	 public final static String hasSearchLimit_uri = "http://inference-web.org/2007/10/service/search.owl#hasSearchLimit";
	 public final static Property  hasSearchLimit = ResourceFactory.createProperty(hasSearchLimit_uri);

	 public final static String hasSearchTotalResults_lname = "hasSearchTotalResults";
	 public final static String hasSearchTotalResults_uri = "http://inference-web.org/2007/10/service/search.owl#hasSearchTotalResults";
	 public final static Property  hasSearchTotalResults = ResourceFactory.createProperty(hasSearchTotalResults_uri);

	 public final static String usesSearchResultSyntax_lname = "usesSearchResultSyntax";
	 public final static String usesSearchResultSyntax_uri = "http://inference-web.org/2007/10/service/search.owl#usesSearchResultSyntax";
	 public final static Property  usesSearchResultSyntax = ResourceFactory.createProperty(usesSearchResultSyntax_uri);

	 public final static String hasSearchSortField_lname = "hasSearchSortField";
	 public final static String hasSearchSortField_uri = "http://inference-web.org/2007/10/service/search.owl#hasSearchSortField";
	 public final static Property  hasSearchSortField = ResourceFactory.createProperty(hasSearchSortField_uri);

	 public final static String hasSearchProcessSeconds_lname = "hasSearchProcessSeconds";
	 public final static String hasSearchProcessSeconds_uri = "http://inference-web.org/2007/10/service/search.owl#hasSearchProcessSeconds";
	 public final static Property  hasSearchProcessSeconds = ResourceFactory.createProperty(hasSearchProcessSeconds_uri);

	 public final static String hasSearchRequest_lname = "hasSearchRequest";
	 public final static String hasSearchRequest_uri = "http://inference-web.org/2007/10/service/search.owl#hasSearchRequest";
	 public final static Property  hasSearchRequest = ResourceFactory.createProperty(hasSearchRequest_uri);

	 public final static String hasSearchSortReverse_lname = "hasSearchSortReverse";
	 public final static String hasSearchSortReverse_uri = "http://inference-web.org/2007/10/service/search.owl#hasSearchSortReverse";
	 public final static Property  hasSearchSortReverse = ResourceFactory.createProperty(hasSearchSortReverse_uri);

	 public final static String isSearchSucceed_lname = "isSearchSucceed";
	 public final static String isSearchSucceed_uri = "http://inference-web.org/2007/10/service/search.owl#isSearchSucceed";
	 public final static Property  isSearchSucceed = ResourceFactory.createProperty(isSearchSucceed_uri);

	 public final static String usesSearchService_lname = "usesSearchService";
	 public final static String usesSearchService_uri = "http://inference-web.org/2007/10/service/search.owl#usesSearchService";
	 public final static Property  usesSearchService = ResourceFactory.createProperty(usesSearchService_uri);

	// Instance (0)


}


 
