/**
 * DCTERMS.java
 *
 *  This file is automatically generated by PML API 
 *	generated on  Sun Dec 20 18:30:12 EST 2009
 *  
 *  @author: Li Ding (http://www.cs.rpi.edu/~dingl )
 *
 */
package  org.inference_web.onto;

import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.ResourceFactory;


/**
 *
 *  
 *  Ontology information 
 *   	label:  n/a
 *   	comment:   To comment on this schema, please contact dcmifb@dublincore.org.
 */
public class DCTERMS{

    protected static final String NS = "http://purl.org/dc/terms/";

    public static final String getURI(){ return NS; }

	// Class (33)
	 public final static String URI_lname = "URI";
	 public final static String URI_qname = "dcterms:URI";
	 public final static String URI_uri = "http://purl.org/dc/terms/URI";
	 public final static Resource  URI = ResourceFactory.createResource(URI_uri);

	 public final static String PeriodOfTime_lname = "PeriodOfTime";
	 public final static String PeriodOfTime_qname = "dcterms:PeriodOfTime";
	 public final static String PeriodOfTime_uri = "http://purl.org/dc/terms/PeriodOfTime";
	 public final static Resource  PeriodOfTime = ResourceFactory.createResource(PeriodOfTime_uri);

	 public final static String MediaTypeOrExtent_lname = "MediaTypeOrExtent";
	 public final static String MediaTypeOrExtent_qname = "dcterms:MediaTypeOrExtent";
	 public final static String MediaTypeOrExtent_uri = "http://purl.org/dc/terms/MediaTypeOrExtent";
	 public final static Resource  MediaTypeOrExtent = ResourceFactory.createResource(MediaTypeOrExtent_uri);

	 public final static String ProvenanceStatement_lname = "ProvenanceStatement";
	 public final static String ProvenanceStatement_qname = "dcterms:ProvenanceStatement";
	 public final static String ProvenanceStatement_uri = "http://purl.org/dc/terms/ProvenanceStatement";
	 public final static Resource  ProvenanceStatement = ResourceFactory.createResource(ProvenanceStatement_uri);

	 public final static String AgentClass_lname = "AgentClass";
	 public final static String AgentClass_qname = "dcterms:AgentClass";
	 public final static String AgentClass_uri = "http://purl.org/dc/terms/AgentClass";
	 public final static Resource  AgentClass = ResourceFactory.createResource(AgentClass_uri);

	 public final static String Point_lname = "Point";
	 public final static String Point_qname = "dcterms:Point";
	 public final static String Point_uri = "http://purl.org/dc/terms/Point";
	 public final static Resource  Point = ResourceFactory.createResource(Point_uri);

	 public final static String Frequency_lname = "Frequency";
	 public final static String Frequency_qname = "dcterms:Frequency";
	 public final static String Frequency_uri = "http://purl.org/dc/terms/Frequency";
	 public final static Resource  Frequency = ResourceFactory.createResource(Frequency_uri);

	 public final static String SizeOrDuration_lname = "SizeOrDuration";
	 public final static String SizeOrDuration_qname = "dcterms:SizeOrDuration";
	 public final static String SizeOrDuration_uri = "http://purl.org/dc/terms/SizeOrDuration";
	 public final static Resource  SizeOrDuration = ResourceFactory.createResource(SizeOrDuration_uri);

	 public final static String W3CDTF_lname = "W3CDTF";
	 public final static String W3CDTF_qname = "dcterms:W3CDTF";
	 public final static String W3CDTF_uri = "http://purl.org/dc/terms/W3CDTF";
	 public final static Resource  W3CDTF = ResourceFactory.createResource(W3CDTF_uri);

	 public final static String PhysicalResource_lname = "PhysicalResource";
	 public final static String PhysicalResource_qname = "dcterms:PhysicalResource";
	 public final static String PhysicalResource_uri = "http://purl.org/dc/terms/PhysicalResource";
	 public final static Resource  PhysicalResource = ResourceFactory.createResource(PhysicalResource_uri);

	 public final static String ISO639_3_lname = "ISO639_3";
	 public final static String ISO639_3_qname = "dcterms:ISO639_3";
	 public final static String ISO639_3_uri = "http://purl.org/dc/terms/ISO639-3";
	 public final static Resource  ISO639_3 = ResourceFactory.createResource(ISO639_3_uri);

	 public final static String ISO639_2_lname = "ISO639_2";
	 public final static String ISO639_2_qname = "dcterms:ISO639_2";
	 public final static String ISO639_2_uri = "http://purl.org/dc/terms/ISO639-2";
	 public final static Resource  ISO639_2 = ResourceFactory.createResource(ISO639_2_uri);

	 public final static String Standard_lname = "Standard";
	 public final static String Standard_qname = "dcterms:Standard";
	 public final static String Standard_uri = "http://purl.org/dc/terms/Standard";
	 public final static Resource  Standard = ResourceFactory.createResource(Standard_uri);

	 public final static String Box_lname = "Box";
	 public final static String Box_qname = "dcterms:Box";
	 public final static String Box_uri = "http://purl.org/dc/terms/Box";
	 public final static Resource  Box = ResourceFactory.createResource(Box_uri);

	 public final static String Period_lname = "Period";
	 public final static String Period_qname = "dcterms:Period";
	 public final static String Period_uri = "http://purl.org/dc/terms/Period";
	 public final static Resource  Period = ResourceFactory.createResource(Period_uri);

	 public final static String Policy_lname = "Policy";
	 public final static String Policy_qname = "dcterms:Policy";
	 public final static String Policy_uri = "http://purl.org/dc/terms/Policy";
	 public final static Resource  Policy = ResourceFactory.createResource(Policy_uri);

	 public final static String Location_lname = "Location";
	 public final static String Location_qname = "dcterms:Location";
	 public final static String Location_uri = "http://purl.org/dc/terms/Location";
	 public final static Resource  Location = ResourceFactory.createResource(Location_uri);

	 public final static String RFC3066_lname = "RFC3066";
	 public final static String RFC3066_qname = "dcterms:RFC3066";
	 public final static String RFC3066_uri = "http://purl.org/dc/terms/RFC3066";
	 public final static Resource  RFC3066 = ResourceFactory.createResource(RFC3066_uri);

	 public final static String Agent_lname = "Agent";
	 public final static String Agent_qname = "dcterms:Agent";
	 public final static String Agent_uri = "http://purl.org/dc/terms/Agent";
	 public final static Resource  Agent = ResourceFactory.createResource(Agent_uri);

	 public final static String LinguisticSystem_lname = "LinguisticSystem";
	 public final static String LinguisticSystem_qname = "dcterms:LinguisticSystem";
	 public final static String LinguisticSystem_uri = "http://purl.org/dc/terms/LinguisticSystem";
	 public final static Resource  LinguisticSystem = ResourceFactory.createResource(LinguisticSystem_uri);

	 public final static String RightsStatement_lname = "RightsStatement";
	 public final static String RightsStatement_qname = "dcterms:RightsStatement";
	 public final static String RightsStatement_uri = "http://purl.org/dc/terms/RightsStatement";
	 public final static Resource  RightsStatement = ResourceFactory.createResource(RightsStatement_uri);

	 public final static String BibliographicResource_lname = "BibliographicResource";
	 public final static String BibliographicResource_qname = "dcterms:BibliographicResource";
	 public final static String BibliographicResource_uri = "http://purl.org/dc/terms/BibliographicResource";
	 public final static Resource  BibliographicResource = ResourceFactory.createResource(BibliographicResource_uri);

	 public final static String FileFormat_lname = "FileFormat";
	 public final static String FileFormat_qname = "dcterms:FileFormat";
	 public final static String FileFormat_uri = "http://purl.org/dc/terms/FileFormat";
	 public final static Resource  FileFormat = ResourceFactory.createResource(FileFormat_uri);

	 public final static String LicenseDocument_lname = "LicenseDocument";
	 public final static String LicenseDocument_qname = "dcterms:LicenseDocument";
	 public final static String LicenseDocument_uri = "http://purl.org/dc/terms/LicenseDocument";
	 public final static Resource  LicenseDocument = ResourceFactory.createResource(LicenseDocument_uri);

	 public final static String ISO3166_lname = "ISO3166";
	 public final static String ISO3166_qname = "dcterms:ISO3166";
	 public final static String ISO3166_uri = "http://purl.org/dc/terms/ISO3166";
	 public final static Resource  ISO3166 = ResourceFactory.createResource(ISO3166_uri);

	 public final static String PhysicalMedium_lname = "PhysicalMedium";
	 public final static String PhysicalMedium_qname = "dcterms:PhysicalMedium";
	 public final static String PhysicalMedium_uri = "http://purl.org/dc/terms/PhysicalMedium";
	 public final static Resource  PhysicalMedium = ResourceFactory.createResource(PhysicalMedium_uri);

	 public final static String RFC1766_lname = "RFC1766";
	 public final static String RFC1766_qname = "dcterms:RFC1766";
	 public final static String RFC1766_uri = "http://purl.org/dc/terms/RFC1766";
	 public final static Resource  RFC1766 = ResourceFactory.createResource(RFC1766_uri);

	 public final static String LocationPeriodOrJurisdiction_lname = "LocationPeriodOrJurisdiction";
	 public final static String LocationPeriodOrJurisdiction_qname = "dcterms:LocationPeriodOrJurisdiction";
	 public final static String LocationPeriodOrJurisdiction_uri = "http://purl.org/dc/terms/LocationPeriodOrJurisdiction";
	 public final static Resource  LocationPeriodOrJurisdiction = ResourceFactory.createResource(LocationPeriodOrJurisdiction_uri);

	 public final static String Jurisdiction_lname = "Jurisdiction";
	 public final static String Jurisdiction_qname = "dcterms:Jurisdiction";
	 public final static String Jurisdiction_uri = "http://purl.org/dc/terms/Jurisdiction";
	 public final static Resource  Jurisdiction = ResourceFactory.createResource(Jurisdiction_uri);

	 public final static String MethodOfAccrual_lname = "MethodOfAccrual";
	 public final static String MethodOfAccrual_qname = "dcterms:MethodOfAccrual";
	 public final static String MethodOfAccrual_uri = "http://purl.org/dc/terms/MethodOfAccrual";
	 public final static Resource  MethodOfAccrual = ResourceFactory.createResource(MethodOfAccrual_uri);

	 public final static String MethodOfInstruction_lname = "MethodOfInstruction";
	 public final static String MethodOfInstruction_qname = "dcterms:MethodOfInstruction";
	 public final static String MethodOfInstruction_uri = "http://purl.org/dc/terms/MethodOfInstruction";
	 public final static Resource  MethodOfInstruction = ResourceFactory.createResource(MethodOfInstruction_uri);

	 public final static String MediaType_lname = "MediaType";
	 public final static String MediaType_qname = "dcterms:MediaType";
	 public final static String MediaType_uri = "http://purl.org/dc/terms/MediaType";
	 public final static Resource  MediaType = ResourceFactory.createResource(MediaType_uri);

	 public final static String RFC4646_lname = "RFC4646";
	 public final static String RFC4646_qname = "dcterms:RFC4646";
	 public final static String RFC4646_uri = "http://purl.org/dc/terms/RFC4646";
	 public final static Resource  RFC4646 = ResourceFactory.createResource(RFC4646_uri);

	// Property (55)
	 public final static String medium_lname = "medium";
	 public final static String medium_qname = "dcterms:medium";
	 public final static String medium_uri = "http://purl.org/dc/terms/medium";
	 public final static Property  medium = ResourceFactory.createProperty(medium_uri);

	 public final static String language_lname = "language";
	 public final static String language_qname = "dcterms:language";
	 public final static String language_uri = "http://purl.org/dc/terms/language";
	 public final static Property  language = ResourceFactory.createProperty(language_uri);

	 public final static String dateCopyrighted_lname = "dateCopyrighted";
	 public final static String dateCopyrighted_qname = "dcterms:dateCopyrighted";
	 public final static String dateCopyrighted_uri = "http://purl.org/dc/terms/dateCopyrighted";
	 public final static Property  dateCopyrighted = ResourceFactory.createProperty(dateCopyrighted_uri);

	 public final static String mediator_lname = "mediator";
	 public final static String mediator_qname = "dcterms:mediator";
	 public final static String mediator_uri = "http://purl.org/dc/terms/mediator";
	 public final static Property  mediator = ResourceFactory.createProperty(mediator_uri);

	 public final static String accessRights_lname = "accessRights";
	 public final static String accessRights_qname = "dcterms:accessRights";
	 public final static String accessRights_uri = "http://purl.org/dc/terms/accessRights";
	 public final static Property  accessRights = ResourceFactory.createProperty(accessRights_uri);

	 public final static String hasVersion_lname = "hasVersion";
	 public final static String hasVersion_qname = "dcterms:hasVersion";
	 public final static String hasVersion_uri = "http://purl.org/dc/terms/hasVersion";
	 public final static Property  hasVersion = ResourceFactory.createProperty(hasVersion_uri);

	 public final static String date_lname = "date";
	 public final static String date_qname = "dcterms:date";
	 public final static String date_uri = "http://purl.org/dc/terms/date";
	 public final static Property  date = ResourceFactory.createProperty(date_uri);

	 public final static String requires_lname = "requires";
	 public final static String requires_qname = "dcterms:requires";
	 public final static String requires_uri = "http://purl.org/dc/terms/requires";
	 public final static Property  requires = ResourceFactory.createProperty(requires_uri);

	 public final static String relation_lname = "relation";
	 public final static String relation_qname = "dcterms:relation";
	 public final static String relation_uri = "http://purl.org/dc/terms/relation";
	 public final static Property  relation = ResourceFactory.createProperty(relation_uri);

	 public final static String available_lname = "available";
	 public final static String available_qname = "dcterms:available";
	 public final static String available_uri = "http://purl.org/dc/terms/available";
	 public final static Property  available = ResourceFactory.createProperty(available_uri);

	 public final static String instructionalMethod_lname = "instructionalMethod";
	 public final static String instructionalMethod_qname = "dcterms:instructionalMethod";
	 public final static String instructionalMethod_uri = "http://purl.org/dc/terms/instructionalMethod";
	 public final static Property  instructionalMethod = ResourceFactory.createProperty(instructionalMethod_uri);

	 public final static String references_lname = "references";
	 public final static String references_qname = "dcterms:references";
	 public final static String references_uri = "http://purl.org/dc/terms/references";
	 public final static Property  references = ResourceFactory.createProperty(references_uri);

	 public final static String created_lname = "created";
	 public final static String created_qname = "dcterms:created";
	 public final static String created_uri = "http://purl.org/dc/terms/created";
	 public final static Property  created = ResourceFactory.createProperty(created_uri);

	 public final static String isFormatOf_lname = "isFormatOf";
	 public final static String isFormatOf_qname = "dcterms:isFormatOf";
	 public final static String isFormatOf_uri = "http://purl.org/dc/terms/isFormatOf";
	 public final static Property  isFormatOf = ResourceFactory.createProperty(isFormatOf_uri);

	 public final static String identifier_lname = "identifier";
	 public final static String identifier_qname = "dcterms:identifier";
	 public final static String identifier_uri = "http://purl.org/dc/terms/identifier";
	 public final static Property  identifier = ResourceFactory.createProperty(identifier_uri);

	 public final static String accrualMethod_lname = "accrualMethod";
	 public final static String accrualMethod_qname = "dcterms:accrualMethod";
	 public final static String accrualMethod_uri = "http://purl.org/dc/terms/accrualMethod";
	 public final static Property  accrualMethod = ResourceFactory.createProperty(accrualMethod_uri);

	 public final static String replaces_lname = "replaces";
	 public final static String replaces_qname = "dcterms:replaces";
	 public final static String replaces_uri = "http://purl.org/dc/terms/replaces";
	 public final static Property  replaces = ResourceFactory.createProperty(replaces_uri);

	 public final static String rights_lname = "rights";
	 public final static String rights_qname = "dcterms:rights";
	 public final static String rights_uri = "http://purl.org/dc/terms/rights";
	 public final static Property  rights = ResourceFactory.createProperty(rights_uri);

	 public final static String modified_lname = "modified";
	 public final static String modified_qname = "dcterms:modified";
	 public final static String modified_uri = "http://purl.org/dc/terms/modified";
	 public final static Property  modified = ResourceFactory.createProperty(modified_uri);

	 public final static String issued_lname = "issued";
	 public final static String issued_qname = "dcterms:issued";
	 public final static String issued_uri = "http://purl.org/dc/terms/issued";
	 public final static Property  issued = ResourceFactory.createProperty(issued_uri);

	 public final static String description_lname = "description";
	 public final static String description_qname = "dcterms:description";
	 public final static String description_uri = "http://purl.org/dc/terms/description";
	 public final static Property  description = ResourceFactory.createProperty(description_uri);

	 public final static String type_lname = "type";
	 public final static String type_qname = "dcterms:type";
	 public final static String type_uri = "http://purl.org/dc/terms/type";
	 public final static Property  type = ResourceFactory.createProperty(type_uri);

	 public final static String accrualPeriodicity_lname = "accrualPeriodicity";
	 public final static String accrualPeriodicity_qname = "dcterms:accrualPeriodicity";
	 public final static String accrualPeriodicity_uri = "http://purl.org/dc/terms/accrualPeriodicity";
	 public final static Property  accrualPeriodicity = ResourceFactory.createProperty(accrualPeriodicity_uri);

	 public final static String isVersionOf_lname = "isVersionOf";
	 public final static String isVersionOf_qname = "dcterms:isVersionOf";
	 public final static String isVersionOf_uri = "http://purl.org/dc/terms/isVersionOf";
	 public final static Property  isVersionOf = ResourceFactory.createProperty(isVersionOf_uri);

	 public final static String audience_lname = "audience";
	 public final static String audience_qname = "dcterms:audience";
	 public final static String audience_uri = "http://purl.org/dc/terms/audience";
	 public final static Property  audience = ResourceFactory.createProperty(audience_uri);

	 public final static String title_lname = "title";
	 public final static String title_qname = "dcterms:title";
	 public final static String title_uri = "http://purl.org/dc/terms/title";
	 public final static Property  title = ResourceFactory.createProperty(title_uri);

	 public final static String bibliographicCitation_lname = "bibliographicCitation";
	 public final static String bibliographicCitation_qname = "dcterms:bibliographicCitation";
	 public final static String bibliographicCitation_uri = "http://purl.org/dc/terms/bibliographicCitation";
	 public final static Property  bibliographicCitation = ResourceFactory.createProperty(bibliographicCitation_uri);

	 public final static String dateAccepted_lname = "dateAccepted";
	 public final static String dateAccepted_qname = "dcterms:dateAccepted";
	 public final static String dateAccepted_uri = "http://purl.org/dc/terms/dateAccepted";
	 public final static Property  dateAccepted = ResourceFactory.createProperty(dateAccepted_uri);

	 public final static String coverage_lname = "coverage";
	 public final static String coverage_qname = "dcterms:coverage";
	 public final static String coverage_uri = "http://purl.org/dc/terms/coverage";
	 public final static Property  coverage = ResourceFactory.createProperty(coverage_uri);

	 public final static String educationLevel_lname = "educationLevel";
	 public final static String educationLevel_qname = "dcterms:educationLevel";
	 public final static String educationLevel_uri = "http://purl.org/dc/terms/educationLevel";
	 public final static Property  educationLevel = ResourceFactory.createProperty(educationLevel_uri);

	 public final static String format_lname = "format";
	 public final static String format_qname = "dcterms:format";
	 public final static String format_uri = "http://purl.org/dc/terms/format";
	 public final static Property  format = ResourceFactory.createProperty(format_uri);

	 public final static String alternative_lname = "alternative";
	 public final static String alternative_qname = "dcterms:alternative";
	 public final static String alternative_uri = "http://purl.org/dc/terms/alternative";
	 public final static Property  alternative = ResourceFactory.createProperty(alternative_uri);

	 public final static String valid_lname = "valid";
	 public final static String valid_qname = "dcterms:valid";
	 public final static String valid_uri = "http://purl.org/dc/terms/valid";
	 public final static Property  valid = ResourceFactory.createProperty(valid_uri);

	 public final static String creator_lname = "creator";
	 public final static String creator_qname = "dcterms:creator";
	 public final static String creator_uri = "http://purl.org/dc/terms/creator";
	 public final static Property  creator = ResourceFactory.createProperty(creator_uri);

	 public final static String source_lname = "source";
	 public final static String source_qname = "dcterms:source";
	 public final static String source_uri = "http://purl.org/dc/terms/source";
	 public final static Property  source = ResourceFactory.createProperty(source_uri);

	 public final static String hasPart_lname = "hasPart";
	 public final static String hasPart_qname = "dcterms:hasPart";
	 public final static String hasPart_uri = "http://purl.org/dc/terms/hasPart";
	 public final static Property  hasPart = ResourceFactory.createProperty(hasPart_uri);

	 public final static String provenance_lname = "provenance";
	 public final static String provenance_qname = "dcterms:provenance";
	 public final static String provenance_uri = "http://purl.org/dc/terms/provenance";
	 public final static Property  provenance = ResourceFactory.createProperty(provenance_uri);

	 public final static String dateSubmitted_lname = "dateSubmitted";
	 public final static String dateSubmitted_qname = "dcterms:dateSubmitted";
	 public final static String dateSubmitted_uri = "http://purl.org/dc/terms/dateSubmitted";
	 public final static Property  dateSubmitted = ResourceFactory.createProperty(dateSubmitted_uri);

	 public final static String abstract_java_lname = "abstract";
	 public final static String abstract_java_qname = "dcterms:abstract";
	 public final static String abstract_java_uri = "http://purl.org/dc/terms/abstract";
	 public final static Property  abstract_java = ResourceFactory.createProperty(abstract_java_uri);

	 public final static String isReferencedBy_lname = "isReferencedBy";
	 public final static String isReferencedBy_qname = "dcterms:isReferencedBy";
	 public final static String isReferencedBy_uri = "http://purl.org/dc/terms/isReferencedBy";
	 public final static Property  isReferencedBy = ResourceFactory.createProperty(isReferencedBy_uri);

	 public final static String license_lname = "license";
	 public final static String license_qname = "dcterms:license";
	 public final static String license_uri = "http://purl.org/dc/terms/license";
	 public final static Property  license = ResourceFactory.createProperty(license_uri);

	 public final static String accrualPolicy_lname = "accrualPolicy";
	 public final static String accrualPolicy_qname = "dcterms:accrualPolicy";
	 public final static String accrualPolicy_uri = "http://purl.org/dc/terms/accrualPolicy";
	 public final static Property  accrualPolicy = ResourceFactory.createProperty(accrualPolicy_uri);

	 public final static String subject_lname = "subject";
	 public final static String subject_qname = "dcterms:subject";
	 public final static String subject_uri = "http://purl.org/dc/terms/subject";
	 public final static Property  subject = ResourceFactory.createProperty(subject_uri);

	 public final static String spatial_lname = "spatial";
	 public final static String spatial_qname = "dcterms:spatial";
	 public final static String spatial_uri = "http://purl.org/dc/terms/spatial";
	 public final static Property  spatial = ResourceFactory.createProperty(spatial_uri);

	 public final static String conformsTo_lname = "conformsTo";
	 public final static String conformsTo_qname = "dcterms:conformsTo";
	 public final static String conformsTo_uri = "http://purl.org/dc/terms/conformsTo";
	 public final static Property  conformsTo = ResourceFactory.createProperty(conformsTo_uri);

	 public final static String isReplacedBy_lname = "isReplacedBy";
	 public final static String isReplacedBy_qname = "dcterms:isReplacedBy";
	 public final static String isReplacedBy_uri = "http://purl.org/dc/terms/isReplacedBy";
	 public final static Property  isReplacedBy = ResourceFactory.createProperty(isReplacedBy_uri);

	 public final static String publisher_lname = "publisher";
	 public final static String publisher_qname = "dcterms:publisher";
	 public final static String publisher_uri = "http://purl.org/dc/terms/publisher";
	 public final static Property  publisher = ResourceFactory.createProperty(publisher_uri);

	 public final static String tableOfContents_lname = "tableOfContents";
	 public final static String tableOfContents_qname = "dcterms:tableOfContents";
	 public final static String tableOfContents_uri = "http://purl.org/dc/terms/tableOfContents";
	 public final static Property  tableOfContents = ResourceFactory.createProperty(tableOfContents_uri);

	 public final static String hasFormat_lname = "hasFormat";
	 public final static String hasFormat_qname = "dcterms:hasFormat";
	 public final static String hasFormat_uri = "http://purl.org/dc/terms/hasFormat";
	 public final static Property  hasFormat = ResourceFactory.createProperty(hasFormat_uri);

	 public final static String rightsHolder_lname = "rightsHolder";
	 public final static String rightsHolder_qname = "dcterms:rightsHolder";
	 public final static String rightsHolder_uri = "http://purl.org/dc/terms/rightsHolder";
	 public final static Property  rightsHolder = ResourceFactory.createProperty(rightsHolder_uri);

	 public final static String contributor_lname = "contributor";
	 public final static String contributor_qname = "dcterms:contributor";
	 public final static String contributor_uri = "http://purl.org/dc/terms/contributor";
	 public final static Property  contributor = ResourceFactory.createProperty(contributor_uri);

	 public final static String isRequiredBy_lname = "isRequiredBy";
	 public final static String isRequiredBy_qname = "dcterms:isRequiredBy";
	 public final static String isRequiredBy_uri = "http://purl.org/dc/terms/isRequiredBy";
	 public final static Property  isRequiredBy = ResourceFactory.createProperty(isRequiredBy_uri);

	 public final static String isPartOf_lname = "isPartOf";
	 public final static String isPartOf_qname = "dcterms:isPartOf";
	 public final static String isPartOf_uri = "http://purl.org/dc/terms/isPartOf";
	 public final static Property  isPartOf = ResourceFactory.createProperty(isPartOf_uri);

	 public final static String extent_lname = "extent";
	 public final static String extent_qname = "dcterms:extent";
	 public final static String extent_uri = "http://purl.org/dc/terms/extent";
	 public final static Property  extent = ResourceFactory.createProperty(extent_uri);

	 public final static String temporal_lname = "temporal";
	 public final static String temporal_qname = "dcterms:temporal";
	 public final static String temporal_uri = "http://purl.org/dc/terms/temporal";
	 public final static Property  temporal = ResourceFactory.createProperty(temporal_uri);

	// Instance (9)
	 public final static String LCSH_lname = "LCSH";
	 public final static String LCSH_qname = "dcterms:LCSH";
	 public final static String LCSH_uri = "http://purl.org/dc/terms/LCSH";
	 public final static Resource  LCSH = ResourceFactory.createResource(LCSH_uri);

	 public final static String TGN_lname = "TGN";
	 public final static String TGN_qname = "dcterms:TGN";
	 public final static String TGN_uri = "http://purl.org/dc/terms/TGN";
	 public final static Resource  TGN = ResourceFactory.createResource(TGN_uri);

	 public final static String NLM_lname = "NLM";
	 public final static String NLM_qname = "dcterms:NLM";
	 public final static String NLM_uri = "http://purl.org/dc/terms/NLM";
	 public final static Resource  NLM = ResourceFactory.createResource(NLM_uri);

	 public final static String DDC_lname = "DDC";
	 public final static String DDC_qname = "dcterms:DDC";
	 public final static String DDC_uri = "http://purl.org/dc/terms/DDC";
	 public final static Resource  DDC = ResourceFactory.createResource(DDC_uri);

	 public final static String LCC_lname = "LCC";
	 public final static String LCC_qname = "dcterms:LCC";
	 public final static String LCC_uri = "http://purl.org/dc/terms/LCC";
	 public final static Resource  LCC = ResourceFactory.createResource(LCC_uri);

	 public final static String DCMIType_lname = "DCMIType";
	 public final static String DCMIType_qname = "dcterms:DCMIType";
	 public final static String DCMIType_uri = "http://purl.org/dc/terms/DCMIType";
	 public final static Resource  DCMIType = ResourceFactory.createResource(DCMIType_uri);

	 public final static String MESH_lname = "MESH";
	 public final static String MESH_qname = "dcterms:MESH";
	 public final static String MESH_uri = "http://purl.org/dc/terms/MESH";
	 public final static Resource  MESH = ResourceFactory.createResource(MESH_uri);

	 public final static String IMT_lname = "IMT";
	 public final static String IMT_qname = "dcterms:IMT";
	 public final static String IMT_uri = "http://purl.org/dc/terms/IMT";
	 public final static Resource  IMT = ResourceFactory.createResource(IMT_uri);

	 public final static String UDC_lname = "UDC";
	 public final static String UDC_qname = "dcterms:UDC";
	 public final static String UDC_uri = "http://purl.org/dc/terms/UDC";
	 public final static Resource  UDC = ResourceFactory.createResource(UDC_uri);



}


 
