/**
 * ARCHIVE.java
 *
 *  This file is automatically generated by PML API 
 *	generated on  Mon May 12 01:29:16 EDT 2008
 *  
 *  @author: Li Ding (http://www.cs.rpi.edu/~dingl )
 *
 */
package  org.inference_web.iwapp.iwsearch;

import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.ResourceFactory;


/**
 *
 *  
 *  Ontology information 
 *   	label:  Semantic Web Archive Ontology@en-US
 *   	comment:   This ontology defines terms for archiving Semantic Web Documents. It also provides some example instances for best practices. This ontology is create by Li Ding (http://www.cs.rpi.edu/~dingl/). @en-US
 */
public class ARCHIVE{

    protected static final String NS = "http://tw.rpi.edu/2008/sw/archive.owl#";

    public static final String getURI(){ return NS; }

	// Class (7)
	 public final static String Crawl_lname = "Crawl";
	 public final static String Crawl_qname = "archive:Crawl";
	 public final static String Crawl_uri = "http://tw.rpi.edu/2008/sw/archive.owl#Crawl";
	 public final static Resource  Crawl = ResourceFactory.createResource(Crawl_uri);

	 public final static String Step_lname = "Step";
	 public final static String Step_qname = "archive:Step";
	 public final static String Step_uri = "http://tw.rpi.edu/2008/sw/archive.owl#Step";
	 public final static Resource  Step = ResourceFactory.createResource(Step_uri);

	 public final static String Revision_lname = "Revision";
	 public final static String Revision_qname = "archive:Revision";
	 public final static String Revision_uri = "http://tw.rpi.edu/2008/sw/archive.owl#Revision";
	 public final static Resource  Revision = ResourceFactory.createResource(Revision_uri);

	 public final static String Submit_lname = "Submit";
	 public final static String Submit_qname = "archive:Submit";
	 public final static String Submit_uri = "http://tw.rpi.edu/2008/sw/archive.owl#Submit";
	 public final static Resource  Submit = ResourceFactory.createResource(Submit_uri);

	 public final static String CrawlTask_lname = "CrawlTask";
	 public final static String CrawlTask_qname = "archive:CrawlTask";
	 public final static String CrawlTask_uri = "http://tw.rpi.edu/2008/sw/archive.owl#CrawlTask";
	 public final static Resource  CrawlTask = ResourceFactory.createResource(CrawlTask_uri);

	 public final static String Revise_lname = "Revise";
	 public final static String Revise_qname = "archive:Revise";
	 public final static String Revise_uri = "http://tw.rpi.edu/2008/sw/archive.owl#Revise";
	 public final static Resource  Revise = ResourceFactory.createResource(Revise_uri);

	 public final static String Download_lname = "Download";
	 public final static String Download_qname = "archive:Download";
	 public final static String Download_uri = "http://tw.rpi.edu/2008/sw/archive.owl#Download";
	 public final static Resource  Download = ResourceFactory.createResource(Download_uri);

	// Property (30)
	 public final static String hasSubmitter_lname = "hasSubmitter";
	 public final static String hasSubmitter_qname = "archive:hasSubmitter";
	 public final static String hasSubmitter_uri = "http://tw.rpi.edu/2008/sw/archive.owl#hasSubmitter";
	 public final static Property  hasSubmitter = ResourceFactory.createProperty(hasSubmitter_uri);

	 public final static String actor_lname = "actor";
	 public final static String actor_qname = "archive:actor";
	 public final static String actor_uri = "http://tw.rpi.edu/2008/sw/archive.owl#actor";
	 public final static Property  actor = ResourceFactory.createProperty(actor_uri);

	 public final static String hasSeedXmlBase_lname = "hasSeedXmlBase";
	 public final static String hasSeedXmlBase_qname = "archive:hasSeedXmlBase";
	 public final static String hasSeedXmlBase_uri = "http://tw.rpi.edu/2008/sw/archive.owl#hasSeedXmlBase";
	 public final static Property  hasSeedXmlBase = ResourceFactory.createProperty(hasSeedXmlBase_uri);

	 public final static String md5sum_lname = "md5sum";
	 public final static String md5sum_qname = "archive:md5sum";
	 public final static String md5sum_uri = "http://tw.rpi.edu/2008/sw/archive.owl#md5sum";
	 public final static Property  md5sum = ResourceFactory.createProperty(md5sum_uri);

	 public final static String cnt_triple_lname = "cnt_triple";
	 public final static String cnt_triple_qname = "archive:cnt_triple";
	 public final static String cnt_triple_uri = "http://tw.rpi.edu/2008/sw/archive.owl#cnt_triple";
	 public final static Property  cnt_triple = ResourceFactory.createProperty(cnt_triple_uri);

	 public final static String hasSnapshot_lname = "hasSnapshot";
	 public final static String hasSnapshot_qname = "archive:hasSnapshot";
	 public final static String hasSnapshot_uri = "http://tw.rpi.edu/2008/sw/archive.owl#hasSnapshot";
	 public final static Property  hasSnapshot = ResourceFactory.createProperty(hasSnapshot_uri);

	 public final static String hasCrawlDepth_lname = "hasCrawlDepth";
	 public final static String hasCrawlDepth_qname = "archive:hasCrawlDepth";
	 public final static String hasCrawlDepth_uri = "http://tw.rpi.edu/2008/sw/archive.owl#hasCrawlDepth";
	 public final static Property  hasCrawlDepth = ResourceFactory.createProperty(hasCrawlDepth_uri);

	 public final static String hasAllowedUrlPattern_lname = "hasAllowedUrlPattern";
	 public final static String hasAllowedUrlPattern_qname = "archive:hasAllowedUrlPattern";
	 public final static String hasAllowedUrlPattern_uri = "http://tw.rpi.edu/2008/sw/archive.owl#hasAllowedUrlPattern";
	 public final static Property  hasAllowedUrlPattern = ResourceFactory.createProperty(hasAllowedUrlPattern_uri);

	 public final static String output_lname = "output";
	 public final static String output_qname = "archive:output";
	 public final static String output_uri = "http://tw.rpi.edu/2008/sw/archive.owl#output";
	 public final static Property  output = ResourceFactory.createProperty(output_uri);

	 public final static String hasDownloadedUrl_lname = "hasDownloadedUrl";
	 public final static String hasDownloadedUrl_qname = "archive:hasDownloadedUrl";
	 public final static String hasDownloadedUrl_uri = "http://tw.rpi.edu/2008/sw/archive.owl#hasDownloadedUrl";
	 public final static Property  hasDownloadedUrl = ResourceFactory.createProperty(hasDownloadedUrl_uri);

	 public final static String hasSeedUrl_lname = "hasSeedUrl";
	 public final static String hasSeedUrl_qname = "archive:hasSeedUrl";
	 public final static String hasSeedUrl_uri = "http://tw.rpi.edu/2008/sw/archive.owl#hasSeedUrl";
	 public final static Property  hasSeedUrl = ResourceFactory.createProperty(hasSeedUrl_uri);

	 public final static String hasSeedRevisionDate_lname = "hasSeedRevisionDate";
	 public final static String hasSeedRevisionDate_qname = "archive:hasSeedRevisionDate";
	 public final static String hasSeedRevisionDate_uri = "http://tw.rpi.edu/2008/sw/archive.owl#hasSeedRevisionDate";
	 public final static Property  hasSeedRevisionDate = ResourceFactory.createProperty(hasSeedRevisionDate_uri);

	 public final static String hasSnapshotRdf_lname = "hasSnapshotRdf";
	 public final static String hasSnapshotRdf_qname = "archive:hasSnapshotRdf";
	 public final static String hasSnapshotRdf_uri = "http://tw.rpi.edu/2008/sw/archive.owl#hasSnapshotRdf";
	 public final static Property  hasSnapshotRdf = ResourceFactory.createProperty(hasSnapshotRdf_uri);

	 public final static String action_lname = "action";
	 public final static String action_qname = "archive:action";
	 public final static String action_uri = "http://tw.rpi.edu/2008/sw/archive.owl#action";
	 public final static Property  action = ResourceFactory.createProperty(action_uri);

	 public final static String input_lname = "input";
	 public final static String input_qname = "archive:input";
	 public final static String input_uri = "http://tw.rpi.edu/2008/sw/archive.owl#input";
	 public final static Property  input = ResourceFactory.createProperty(input_uri);

	 public final static String xmlbase_lname = "xmlbase";
	 public final static String xmlbase_qname = "archive:xmlbase";
	 public final static String xmlbase_uri = "http://tw.rpi.edu/2008/sw/archive.owl#xmlbase";
	 public final static Property  xmlbase = ResourceFactory.createProperty(xmlbase_uri);

	 public final static String hasInterestedUrlPattern_lname = "hasInterestedUrlPattern";
	 public final static String hasInterestedUrlPattern_qname = "archive:hasInterestedUrlPattern";
	 public final static String hasInterestedUrlPattern_uri = "http://tw.rpi.edu/2008/sw/archive.owl#hasInterestedUrlPattern";
	 public final static Property  hasInterestedUrlPattern = ResourceFactory.createProperty(hasInterestedUrlPattern_uri);

	 public final static String isOriginal_lname = "isOriginal";
	 public final static String isOriginal_qname = "archive:isOriginal";
	 public final static String isOriginal_uri = "http://tw.rpi.edu/2008/sw/archive.owl#isOriginal";
	 public final static Property  isOriginal = ResourceFactory.createProperty(isOriginal_uri);

	 public final static String lastmodified_lname = "lastmodified";
	 public final static String lastmodified_qname = "archive:lastmodified";
	 public final static String lastmodified_uri = "http://tw.rpi.edu/2008/sw/archive.owl#lastmodified";
	 public final static Property  lastmodified = ResourceFactory.createProperty(lastmodified_uri);

	 public final static String cnt_byte_lname = "cnt_byte";
	 public final static String cnt_byte_qname = "archive:cnt_byte";
	 public final static String cnt_byte_uri = "http://tw.rpi.edu/2008/sw/archive.owl#cnt_byte";
	 public final static Property  cnt_byte = ResourceFactory.createProperty(cnt_byte_uri);

	 public final static String hasCrawledSeedUrl_lname = "hasCrawledSeedUrl";
	 public final static String hasCrawledSeedUrl_qname = "archive:hasCrawledSeedUrl";
	 public final static String hasCrawledSeedUrl_uri = "http://tw.rpi.edu/2008/sw/archive.owl#hasCrawledSeedUrl";
	 public final static Property  hasCrawledSeedUrl = ResourceFactory.createProperty(hasCrawledSeedUrl_uri);

	 public final static String hasDisallowedUrlPattern_lname = "hasDisallowedUrlPattern";
	 public final static String hasDisallowedUrlPattern_qname = "archive:hasDisallowedUrlPattern";
	 public final static String hasDisallowedUrlPattern_uri = "http://tw.rpi.edu/2008/sw/archive.owl#hasDisallowedUrlPattern";
	 public final static Property  hasDisallowedUrlPattern = ResourceFactory.createProperty(hasDisallowedUrlPattern_uri);

	 public final static String isVersionOf_lname = "isVersionOf";
	 public final static String isVersionOf_qname = "archive:isVersionOf";
	 public final static String isVersionOf_uri = "http://tw.rpi.edu/2008/sw/archive.owl#isVersionOf";
	 public final static Property  isVersionOf = ResourceFactory.createProperty(isVersionOf_uri);

	 public final static String hasVersion_lname = "hasVersion";
	 public final static String hasVersion_qname = "archive:hasVersion";
	 public final static String hasVersion_uri = "http://tw.rpi.edu/2008/sw/archive.owl#hasVersion";
	 public final static Property  hasVersion = ResourceFactory.createProperty(hasVersion_uri);

	 public final static String hasNextVersion_lname = "hasNextVersion";
	 public final static String hasNextVersion_qname = "archive:hasNextVersion";
	 public final static String hasNextVersion_uri = "http://tw.rpi.edu/2008/sw/archive.owl#hasNextVersion";
	 public final static Property  hasNextVersion = ResourceFactory.createProperty(hasNextVersion_uri);

	 public final static String result_lname = "result";
	 public final static String result_qname = "archive:result";
	 public final static String result_uri = "http://tw.rpi.edu/2008/sw/archive.owl#result";
	 public final static Property  result = ResourceFactory.createProperty(result_uri);

	 public final static String charset_lname = "charset";
	 public final static String charset_qname = "archive:charset";
	 public final static String charset_uri = "http://tw.rpi.edu/2008/sw/archive.owl#charset";
	 public final static Property  charset = ResourceFactory.createProperty(charset_uri);

	 public final static String reference_id_lname = "reference_id";
	 public final static String reference_id_qname = "archive:reference_id";
	 public final static String reference_id_uri = "http://tw.rpi.edu/2008/sw/archive.owl#reference_id";
	 public final static Property  reference_id = ResourceFactory.createProperty(reference_id_uri);

	 public final static String onto_ratio_lname = "onto_ratio";
	 public final static String onto_ratio_qname = "archive:onto_ratio";
	 public final static String onto_ratio_uri = "http://tw.rpi.edu/2008/sw/archive.owl#onto_ratio";
	 public final static Property  onto_ratio = ResourceFactory.createProperty(onto_ratio_uri);

	 public final static String hasPreviousVersion_lname = "hasPreviousVersion";
	 public final static String hasPreviousVersion_qname = "archive:hasPreviousVersion";
	 public final static String hasPreviousVersion_uri = "http://tw.rpi.edu/2008/sw/archive.owl#hasPreviousVersion";
	 public final static Property  hasPreviousVersion = ResourceFactory.createProperty(hasPreviousVersion_uri);

	// Instance (18)
	 public final static String SwaDownloader_lname = "SwaDownloader";
	 public final static String SwaDownloader_qname = "archive:SwaDownloader";
	 public final static String SwaDownloader_uri = "http://tw.rpi.edu/2008/sw/archive.owl#SwaDownloader";
	 public final static Resource  SwaDownloader = ResourceFactory.createResource(SwaDownloader_uri);

	 public final static String download_1834_lname = "download_1834";
	 public final static String download_1834_qname = "archive:download_1834";
	 public final static String download_1834_uri = "http://tw.rpi.edu/2008/sw/archive.owl#download_1834";
	 public final static Resource  download_1834 = ResourceFactory.createResource(download_1834_uri);

	 public final static String task_2007_05_30_lname = "task_2007_05_30";
	 public final static String task_2007_05_30_qname = "archive:task_2007_05_30";
	 public final static String task_2007_05_30_uri = "http://tw.rpi.edu/2008/sw/archive.owl#task_2007_05_30";
	 public final static Resource  task_2007_05_30 = ResourceFactory.createResource(task_2007_05_30_uri);

	 public final static String HTML_lname = "HTML";
	 public final static String HTML_qname = "archive:HTML";
	 public final static String HTML_uri = "http://tw.rpi.edu/2008/sw/archive.owl#HTML";
	 public final static Resource  HTML = ResourceFactory.createResource(HTML_uri);

	 public final static String revision_1834_lname = "revision_1834";
	 public final static String revision_1834_qname = "archive:revision_1834";
	 public final static String revision_1834_uri = "http://tw.rpi.edu/2008/sw/archive.owl#revision_1834";
	 public final static Resource  revision_1834 = ResourceFactory.createResource(revision_1834_uri);

	 public final static String RDFA_lname = "RDFA";
	 public final static String RDFA_qname = "archive:RDFA";
	 public final static String RDFA_uri = "http://tw.rpi.edu/2008/sw/archive.owl#RDFA";
	 public final static Resource  RDFA = ResourceFactory.createResource(RDFA_uri);

	 public final static String SwaCrawler_lname = "SwaCrawler";
	 public final static String SwaCrawler_qname = "archive:SwaCrawler";
	 public final static String SwaCrawler_uri = "http://tw.rpi.edu/2008/sw/archive.owl#SwaCrawler";
	 public final static Resource  SwaCrawler = ResourceFactory.createResource(SwaCrawler_uri);

	 public final static String PML_lname = "PML";
	 public final static String PML_qname = "archive:PML";
	 public final static String PML_uri = "http://tw.rpi.edu/2008/sw/archive.owl#PML";
	 public final static Resource  PML = ResourceFactory.createResource(PML_uri);

	 public final static String Swoogle_lname = "Swoogle";
	 public final static String Swoogle_qname = "archive:Swoogle";
	 public final static String Swoogle_uri = "http://tw.rpi.edu/2008/sw/archive.owl#Swoogle";
	 public final static Resource  Swoogle = ResourceFactory.createResource(Swoogle_uri);

	 public final static String crawl_task_2007_05_30_lname = "crawl_task_2007_05_30";
	 public final static String crawl_task_2007_05_30_qname = "archive:crawl_task_2007_05_30";
	 public final static String crawl_task_2007_05_30_uri = "http://tw.rpi.edu/2008/sw/archive.owl#crawl_task_2007_05_30";
	 public final static Resource  crawl_task_2007_05_30 = ResourceFactory.createResource(crawl_task_2007_05_30_uri);

	 public final static String NT_lname = "NT";
	 public final static String NT_qname = "archive:NT";
	 public final static String NT_uri = "http://tw.rpi.edu/2008/sw/archive.owl#NT";
	 public final static Resource  NT = ResourceFactory.createResource(NT_uri);

	 public final static String SemanticWebArchive_lname = "SemanticWebArchive";
	 public final static String SemanticWebArchive_qname = "archive:SemanticWebArchive";
	 public final static String SemanticWebArchive_uri = "http://tw.rpi.edu/2008/sw/archive.owl#SemanticWebArchive";
	 public final static Resource  SemanticWebArchive = ResourceFactory.createResource(SemanticWebArchive_uri);

	 public final static String FOAF_lname = "FOAF";
	 public final static String FOAF_qname = "archive:FOAF";
	 public final static String FOAF_uri = "http://tw.rpi.edu/2008/sw/archive.owl#FOAF";
	 public final static Resource  FOAF = ResourceFactory.createResource(FOAF_uri);

	 public final static String N3_lname = "N3";
	 public final static String N3_qname = "archive:N3";
	 public final static String N3_uri = "http://tw.rpi.edu/2008/sw/archive.owl#N3";
	 public final static Resource  N3 = ResourceFactory.createResource(N3_uri);

	 public final static String Embedded_RDFXML_lname = "Embedded_RDFXML";
	 public final static String Embedded_RDFXML_qname = "archive:Embedded_RDFXML";
	 public final static String Embedded_RDFXML_uri = "http://tw.rpi.edu/2008/sw/archive.owl#Embedded_RDFXML";
	 public final static Resource  Embedded_RDFXML = ResourceFactory.createResource(Embedded_RDFXML_uri);

	 public final static String RDFXML_lname = "RDFXML";
	 public final static String RDFXML_qname = "archive:RDFXML";
	 public final static String RDFXML_uri = "http://tw.rpi.edu/2008/sw/archive.owl#RDFXML";
	 public final static Resource  RDFXML = ResourceFactory.createResource(RDFXML_uri);

	 public final static String task_2007_05_30_1999_lname = "task_2007_05_30_1999";
	 public final static String task_2007_05_30_1999_qname = "archive:task_2007_05_30_1999";
	 public final static String task_2007_05_30_1999_uri = "http://tw.rpi.edu/2008/sw/archive.owl#task_2007_05_30_1999";
	 public final static Resource  task_2007_05_30_1999 = ResourceFactory.createResource(task_2007_05_30_1999_uri);

	 public final static String download_output_1834_lname = "download_output_1834";
	 public final static String download_output_1834_qname = "archive:download_output_1834";
	 public final static String download_output_1834_uri = "http://tw.rpi.edu/2008/sw/archive.owl#download_output_1834";
	 public final static Resource  download_output_1834 = ResourceFactory.createResource(download_output_1834_uri);



}


 
